import type {
  DashboardStats,
  Executive,
  LRRequest,
  Notification,
} from "../types";

const now = new Date();
const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const lastWeek = new Date(today);
lastWeek.setDate(lastWeek.getDate() - 5);

function iso(date: Date, hours = 10, minutes = 30) {
  const d = new Date(date);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalLrs: 25,
  pending: 3,
  approved: 12,
  rejected: 2,
  delivered: 8,
  inTransit: 0,
  freightTotal: 185400,
  approvalRate: 86,
};

export const MOCK_LRS: LRRequest[] = [
  {
    id: "lr-1",
    lrNumber: "VLP/2026/00142",
    trackingId: "TRK-00142",
    consignorName: "ABC Industries",
    consignorAddress: "Plot 12, GIDC, Ahmedabad",
    consigneeName: "Metro Retail",
    consigneeAddress: "HITEC City, Hyderabad",
    consigneePhone: "9012343218",
    originCity: "Ahmedabad",
    destinationCity: "Hyderabad",
    vehicleNumber: "GJ01AB1234",
    goodsDescription: "Electronics",
    noOfPackages: 12,
    weightKg: 450,
    declaredValue: 250000,
    freightAmount: 18500,
    paymentMode: "To Pay",
    dispatchDate: iso(today, 9, 15),
    photos: [],
    status: "approved",
    createdAt: iso(today, 9, 15),
    executive: { name: "Ravi Kumar", mobile: "9012343218" },
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
  {
    id: "lr-2",
    lrNumber: "VLP/2026/00141",
    trackingId: "TRK-00141",
    consignorName: "Sunrise Traders",
    consignorAddress: "Ring Road, Surat",
    consigneeName: "City Mart",
    consigneeAddress: "Banjara Hills, Hyderabad",
    consigneePhone: "9876543210",
    originCity: "Surat",
    destinationCity: "Hyderabad",
    vehicleNumber: "GJ05CD5678",
    goodsDescription: "Textiles",
    noOfPackages: 24,
    weightKg: 820,
    declaredValue: 120000,
    freightAmount: 14200,
    paymentMode: "Paid",
    dispatchDate: iso(today, 11, 50),
    photos: [],
    status: "pending",
    createdAt: iso(today, 11, 50),
    executive: { name: "Ravi Kumar", mobile: "9012343218" },
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
  {
    id: "lr-3",
    lrNumber: "VLP/2026/00138",
    trackingId: "TRK-00138",
    consignorName: "Green Agro",
    consignorAddress: "Nashik Highway",
    consigneeName: "Fresh Stores",
    consigneeAddress: "Madhapur, Hyderabad",
    consigneePhone: "9123456780",
    originCity: "Nashik",
    destinationCity: "Hyderabad",
    vehicleNumber: "MH12EF9012",
    goodsDescription: "Agro products",
    noOfPackages: 8,
    weightKg: 320,
    declaredValue: 45000,
    freightAmount: 6800,
    paymentMode: "To Be Billed",
    dispatchDate: iso(yesterday, 16, 20),
    photos: [],
    status: "delivered",
    createdAt: iso(yesterday, 16, 20),
    deliveredAt: iso(today, 8, 0),
    executive: { name: "Priya Sharma", mobile: "9988776655" },
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
  {
    id: "lr-4",
    lrNumber: "VLP/2026/00135",
    trackingId: "TRK-00135",
    consignorName: "Steel Works",
    consignorAddress: "Jamshedpur",
    consigneeName: "BuildRight",
    consigneeAddress: "Uppal, Hyderabad",
    consigneePhone: "9090909090",
    originCity: "Jamshedpur",
    destinationCity: "Hyderabad",
    vehicleNumber: "JH10GH3456",
    goodsDescription: "Steel rods",
    noOfPackages: 40,
    weightKg: 2400,
    declaredValue: 500000,
    freightAmount: 32000,
    paymentMode: "To Pay",
    dispatchDate: iso(yesterday, 10, 0),
    photos: [],
    status: "rejected",
    rejectionReason: "Incomplete documentation",
    signatureUrl: "https://placehold.co/200x80/png",
    createdAt: iso(yesterday, 10, 0),
    executive: { name: "Amit Patel", mobile: "8877665544" },
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
  {
    id: "lr-5",
    lrNumber: "VLP/2026/00130",
    trackingId: "TRK-00130",
    consignorName: "Chennai Fabrics",
    consignorAddress: "Ambattur, Chennai",
    consigneeName: "Style Hub",
    consigneeAddress: "Kukatpally, Hyderabad",
    consigneePhone: "9000012345",
    originCity: "Chennai",
    destinationCity: "Hyderabad",
    vehicleNumber: "TN09IJ7890",
    goodsDescription: "Garments",
    noOfPackages: 16,
    weightKg: 280,
    declaredValue: 90000,
    freightAmount: 9500,
    paymentMode: "Paid",
    dispatchDate: iso(lastWeek, 14, 30),
    photos: [],
    status: "approved",
    createdAt: iso(lastWeek, 14, 30),
    executive: { name: "Ravi Kumar", mobile: "9012343218" },
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
];

export const MOCK_EXECUTIVES: Executive[] = [
  {
    id: "exec-1",
    name: "Ravi Kumar",
    mobile: "9012343218",
    status: "active",
    lrsThisMonth: 8,
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
  {
    id: "exec-2",
    name: "Priya Sharma",
    mobile: "9988776655",
    status: "active",
    lrsThisMonth: 5,
    branch: { id: "dev-branch-2", name: "Chennai Branch", city: "Chennai" },
  },
  {
    id: "exec-3",
    name: "Amit Patel",
    mobile: "8877665544",
    status: "active",
    lrsThisMonth: 3,
    branch: { id: "dev-branch-1", name: "Hyderabad Branch", city: "Hyderabad" },
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    title: "New LR Request From Ravi Kumar",
    message: "LR VLP/2026/00141 is pending approval",
    lrId: "lr-2",
    read: false,
    createdAt: iso(today, 11, 50),
  },
  {
    id: "notif-2",
    title: "LR Approved — VLP/2026/00142",
    message: "LR has been approved successfully",
    lrId: "lr-1",
    read: false,
    createdAt: iso(today, 9, 30),
  },
  {
    id: "notif-3",
    title: "LR Delivered — VLP/2026/00138",
    message: "Delivery confirmed by executive",
    lrId: "lr-3",
    read: true,
    createdAt: iso(yesterday, 16, 45),
  },
];

export const MOCK_BRANCHES = [
  {
    id: "dev-branch-1",
    name: "Hyderabad Branch",
    city: "Hyderabad",
    state: "Telangana",
    executiveCount: 2,
    lrsThisMonth: 18,
  },
  {
    id: "dev-branch-2",
    name: "Chennai Branch",
    city: "Chennai",
    state: "Tamil Nadu",
    executiveCount: 1,
    lrsThisMonth: 7,
  },
];

export const MOCK_COMPANY = {
  id: "dev-company-1",
  name: "SR Transport",
  address: "Plot 8B, Industries Park, Hyderabad - 500032, Telangana",
  gstNumber: "36AABCA1234M1ZX",
  lrCode: "VLP",
  logoUrl: undefined,
  stampUrl: undefined,
  maxBranches: 5,
  maxExecutives: 20,
  maxLrPerMonth: 500,
  status: "active" as const,
};
